### ISSUE TITLE
from genelab study id to pubmed

### ISSUE THREAD

**Issue by naarkhoo** [nasa/GeneLab_Data_Processing#11]
Hi, 

how can I map genelab study id into pubmed id ?
For example for the study id OSD-70 I would like find the related pubmed id - from the filenames I can see there are GSE33779 and then I can go into https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE33779 citation and see the [23806134](https://www.ncbi.nlm.nih.gov/pubmed/23806134)

is there any smarter way of mapping ?

**Comment by asaravia-butler** [comment]
HI

> Hi,
> 
> how can I map genelab study id into pubmed id ? For example for the study id OSD-70 I would like find the related pubmed id - from the filenames I can see there are GSE33779 and then I can go into https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE33779 citation and see the [23806134](https://www.ncbi.nlm.nih.gov/pubmed/23806134)
> 
> is there any smarter way of mapping ?

If you go to "Publications" on the left panel in the OSDR for OSD-70 (https://osdr.nasa.gov/bio/repo/data/studies/OSD-70) (or any ingested dataset on the [OSDR](https://osdr.nasa.gov/bio/repo)), you will see a link to the publication associated with the ingested data and the PubMed ID.
